### ISSUE TITLE
Modbus Register zum Schreiben

### ISSUE THREAD

**Issue by Senbei123** [daschaefer/SymconPluggit#1]
Hallo,

ich würde gerne meine Pluggit über Home Assistant steuern und kann auch per Modbus die Parameter lesen.
Welches Register nutzt du, um Werte zurück zu schreiben in die Anlage (für die Lüfterstufe, z.B.).

Dank dir im Voraus.

Gruß,
Tristan

**Comment by starlein** [comment]
Hallo,
Lüfterstufe setze ich mittels der Funktion `PLUG_SetFanSpeedLevel` . 
Mit modbus musst du dich doch gar nicht rumschlagen wenn du das Modul hier installiert hast.
